import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/api";
import type { PaymentRecord } from "../lib/types";

const months=["January","February","March","April","May","June","July","August","September","October","November","December"];
function localNow(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Colombo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const g=(x:string)=>p.find(v=>v.type===x)?.value||"";const m=Number(g("month"));return {date:`${g("year")}-${g("month")}-${g("day")}`,year:Number(g("year")),month:months[m-1]};}
function money(v:number){return new Intl.NumberFormat("en-LK",{style:"currency",currency:"LKR",maximumFractionDigits:0}).format(v||0)}

export default function PaymentsPage(){
 const now=localNow();const qc=useQueryClient();
 const students=useQuery({queryKey:["students"],queryFn:api.students});
 const methods=useQuery({queryKey:["reference","Payment Method"],queryFn:()=>api.reference("Payment Method")});
 const payments=useQuery({queryKey:["payments"],queryFn:api.payments});
 const [form,setForm]=useState({studentId:"",year:String(now.year),month:now.month,paymentDate:now.date,amount:"",method:"Cash",receiptRef:"",notes:""});
 const [newMethod,setNewMethod]=useState("");
 const [error,setError]=useState("");
 const [result,setResult]=useState<{paymentId:string;balanceAfter:number;status:string}|null>(null);
 const [actionNotice,setActionNotice]=useState("");
 const [action,setAction]=useState<{mode:"correct"|"void";record:PaymentRecord}|null>(null);
 const [edit,setEdit]=useState({amount:"",paymentDate:"",method:"Cash",receiptRef:"",notes:"",reason:""});
 const activeStudents=useMemo(()=>students.data?.filter(s=>s.status.toLowerCase()==="active")||[],[students.data]);
 const studentNames=useMemo(()=>new Map((students.data||[]).map(s=>[s.id,s.name])),[students.data]);
 const selected=activeStudents.find(s=>s.id===form.studentId);
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const addMethod=useMutation({mutationFn:()=>api.addReference("Payment Method",newMethod),onSuccess:async r=>{await qc.invalidateQueries({queryKey:["reference","Payment Method"]});set("method",r.value);setNewMethod("");},onError:e=>setError((e as Error).message)});
 const record=useMutation({mutationFn:()=>api.recordPayment({studentId:form.studentId,year:Number(form.year),month:form.month,paymentDate:form.paymentDate,amount:Number(form.amount),paymentMethod:form.method,receiptRef:form.receiptRef,notes:form.notes}),onSuccess:async r=>{setResult({paymentId:r.paymentId,balanceAfter:r.balanceAfter,status:r.status});set("amount","");await Promise.all([qc.invalidateQueries({queryKey:["payments"]}),qc.invalidateQueries({queryKey:["dashboard"]}),qc.invalidateQueries({queryKey:["students"]})]);},onError:e=>setError((e as Error).message)});
 const correct=useMutation({mutationFn:()=>{if(!action) throw new Error("Select a payment first.");return api.correctPayment(action.record.id,{amount:Number(edit.amount),paymentDate:edit.paymentDate,paymentMethod:edit.method,receiptRef:edit.receiptRef,notes:edit.notes,reason:edit.reason,expectedVersion:action.record.version});},onSuccess:async r=>{setActionNotice(`Payment ${r.paymentId} corrected successfully.`);setAction(null);await Promise.all([qc.invalidateQueries({queryKey:["payments"]}),qc.invalidateQueries({queryKey:["dashboard"]}),qc.invalidateQueries({queryKey:["students"]})]);},onError:e=>setError((e as Error).message)});
 const voidPayment=useMutation({mutationFn:()=>{if(!action) throw new Error("Select a payment first.");return api.voidPayment(action.record.id,edit.reason,action.record.version);},onSuccess:async r=>{setActionNotice(`Payment ${r.paymentId} was voided. The original transaction remains in history.`);setAction(null);await Promise.all([qc.invalidateQueries({queryKey:["payments"]}),qc.invalidateQueries({queryKey:["dashboard"]}),qc.invalidateQueries({queryKey:["students"]})]);},onError:e=>setError((e as Error).message)});
 const submit=(e:React.FormEvent)=>{e.preventDefault();setError("");setResult(null);setActionNotice("");record.mutate();};
 const openCorrect=(r:PaymentRecord)=>{setError("");setAction({mode:"correct",record:r});setEdit({amount:String(r.amount),paymentDate:r.paymentDate,method:r.paymentMethod||"Cash",receiptRef:r.receiptRef||"",notes:r.notes||"",reason:""});};
 const openVoid=(r:PaymentRecord)=>{setError("");setAction({mode:"void",record:r});setEdit({amount:String(r.amount),paymentDate:r.paymentDate,method:r.paymentMethod||"Cash",receiptRef:r.receiptRef||"",notes:r.notes||"",reason:""});};
 return <>
  <div className="page-title"><div><h1>Fees & Payments</h1><p>Admin-only payment entry with permanent transaction history and safe corrections.</p></div></div>
  {error&&<div className="form-error page-error"><b>!</b><span>{error}</span></div>}
  {result&&<div className="payment-success"><b>✓ Payment recorded</b><span>{result.paymentId} · {result.status} · Balance {money(result.balanceAfter)}</span></div>}
  {actionNotice&&<div className="success-banner">✓ {actionNotice}</div>}
  <div className="payment-layout"><form className="payment-form" onSubmit={submit}><div className="form-section"><h3>Student & Month</h3><div className="form-grid"><label className="span-2">Student *<select required value={form.studentId} onChange={e=>set("studentId",e.target.value)}><option value="">Select student…</option>{activeStudents.map(s=><option key={s.id} value={s.id}>{s.name} — {s.id}</option>)}</select></label><label>Month<select value={form.month} onChange={e=>set("month",e.target.value)}>{months.map(m=><option key={m}>{m}</option>)}</select></label><label>Year<input type="number" value={form.year} onChange={e=>set("year",e.target.value)} min="2000" max="2200"/></label></div></div>
   <div className="form-section"><h3>Payment</h3><div className="form-grid"><label>Amount Received *<input required type="number" min="1" step="1" inputMode="decimal" value={form.amount} onChange={e=>set("amount",e.target.value)} placeholder="3500"/></label><label>Paid Date *<input required type="date" value={form.paymentDate} onChange={e=>set("paymentDate",e.target.value)}/></label><label>Payment Method *<select value={form.method} onChange={e=>set("method",e.target.value)}>{methods.data?.map(x=><option key={x.id} value={x.value}>{x.value}</option>)}</select></label><div className="smart-add"><span>Add new method</span><div><input value={newMethod} onChange={e=>setNewMethod(e.target.value)} placeholder="e.g. QR Payment"/><button type="button" className="secondary-button" disabled={!newMethod.trim()||addMethod.isPending} onClick={()=>addMethod.mutate()}>Add</button></div></div><label>Receipt / Ref<input value={form.receiptRef} onChange={e=>set("receiptRef",e.target.value)}/></label><label>Notes<input value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div></div>
   <button className="primary-button payment-submit" disabled={record.isPending}>{record.isPending?"Saving to Google Sheet…":"Record Payment"}</button></form>
   <aside className="payment-summary"><h3>Selected student</h3>{selected?<><strong>{selected.name}</strong><span>{selected.id}</span><div><small>Current monthly fee</small><b>{money(selected.currentFee||selected.startingFee||0)}</b></div><p>The backend checks the exact selected month's historical fee and remaining balance before accepting a payment.</p></>:<p>Select a student to see their current fee information.</p>}</aside>
  </div>

  <section className="history-section">
   <div className="history-header"><div><h2>Payment history</h2><p>Correct mistakes or void a transaction without deleting the permanent record.</p></div><span>{payments.data?.length||0} records</span></div>
   {payments.isLoading?<div className="state-card"><div className="spinner"/><strong>Loading payments…</strong></div>:payments.isError?<div className="state-card error-state"><b>!</b><strong>Payment history could not be loaded.</strong><span>{(payments.error as Error).message}</span></div>:(payments.data?.length||0)===0?<div className="empty-card"><b>₨</b><h3>No payments yet</h3><p>Recorded payments will appear here.</p></div>:<div className="record-list">{payments.data?.slice(0,30).map(r=><article className="record-card" key={r.id}><div className="record-main"><strong>{studentNames.get(r.studentId)||r.studentId}</strong><span>{r.studentId} · {r.month} {r.year} · {r.paymentDate||"No date"}</span><small>{r.id} · Version {r.version}{r.receiptRef?` · Ref ${r.receiptRef}`:""}</small></div><div className="record-value"><b>{money(r.amount)}</b><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span></div><div className="record-actions">{r.status.toLowerCase()==="active"?<><button className="secondary-button" onClick={()=>openCorrect(r)}>Correct</button><button className="danger-button" onClick={()=>openVoid(r)}>Void</button></>:<span className="muted-label">Permanent history</span>}</div></article>)}</div>}
  </section>

  {action&&<div className="modal-backdrop"><section className="modal-panel compact"><div className="modal-header"><div><h2>{action.mode==="correct"?"Correct payment":"Void payment"}</h2><p>{action.record.id} · Version {action.record.version}</p></div><button className="icon-button" onClick={()=>setAction(null)}>×</button></div><form onSubmit={e=>{e.preventDefault();setError("");action.mode==="correct"?correct.mutate():voidPayment.mutate();}}>{action.mode==="correct"?<div className="form-section"><div className="form-grid"><label>Amount *<input required type="number" min="0.01" step="0.01" value={edit.amount} onChange={e=>setEdit(x=>({...x,amount:e.target.value}))}/></label><label>Payment date *<input required type="date" value={edit.paymentDate} onChange={e=>setEdit(x=>({...x,paymentDate:e.target.value}))}/></label><label>Payment method *<select value={edit.method} onChange={e=>setEdit(x=>({...x,method:e.target.value}))}>{methods.data?.map(x=><option key={x.id} value={x.value}>{x.value}</option>)}</select></label><label>Receipt / Ref<input value={edit.receiptRef} onChange={e=>setEdit(x=>({...x,receiptRef:e.target.value}))}/></label><label className="span-2">Notes<textarea rows={3} value={edit.notes} onChange={e=>setEdit(x=>({...x,notes:e.target.value}))}/></label><label className="span-2">Correction reason *<textarea required rows={3} value={edit.reason} onChange={e=>setEdit(x=>({...x,reason:e.target.value}))} placeholder="Why is this payment being changed?"/></label></div></div>:<div className="form-section"><div className="danger-note"><strong>This does not delete the payment.</strong><span>It changes the transaction to Voided, removes it from fee totals, and keeps a permanent audit history.</span></div><div className="form-grid"><label className="span-2">Void reason *<textarea required rows={4} value={edit.reason} onChange={e=>setEdit(x=>({...x,reason:e.target.value}))} placeholder="Why must this payment be voided?"/></label></div></div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setAction(null)}>Cancel</button><button className={action.mode==="void"?"danger-button":"primary-button"} disabled={!edit.reason.trim()||correct.isPending||voidPayment.isPending}>{action.mode==="void"?(voidPayment.isPending?"Voiding…":"Void Payment"):(correct.isPending?"Saving correction…":"Save Correction")}</button></div></form></section></div>}
 </>;
}
